import { spawn } from 'node:child_process';
import { mkdirSync,writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { once } from 'node:events';
import { app } from './fixture.mjs';
if(!app.listening)await once(app,'listening');
const output=resolve('test-results');mkdirSync(output,{recursive:true});
const chrome=spawn(process.env.BROWSER_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--disable-extensions','--remote-debugging-port=0',`--user-data-dir=${resolve('test-results/chrome-profile')}`,'about:blank'],{windowsHide:true,stdio:['ignore','ignore','pipe']});
let stderr='';
const url=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Chrome did not start: '+stderr)),20000);chrome.stderr.on('data',d=>{stderr+=d;const m=stderr.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(m){clearTimeout(timer);resolve(m[1]);}});chrome.on('error',reject);chrome.on('exit',code=>reject(new Error('Chrome exited '+code+' '+stderr)));});
const ws=new WebSocket(url);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});
let seq=0,session;const pending=new Map(),exceptions=[];
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);if(!p)return;pending.delete(m.id);clearTimeout(p.timer);if(m.error)p.reject(new Error(JSON.stringify(m.error)));else p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')exceptions.push(m.params.exceptionDetails);};
const send=(method,params={},sid=session)=>new Promise((resolve,reject)=>{const id=++seq;const timer=setTimeout(()=>{pending.delete(id);reject(new Error(`Browser command timed out: ${method}`));},10000);pending.set(id,{resolve,reject,timer});ws.send(JSON.stringify({id,method,params,...(sid?{sessionId:sid}:{})}));});
const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const waitFor=async expression=>{for(let n=0;n<100;n++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,50));}throw new Error('Timeout: '+expression);};
const click=async expression=>{await evaluate(`${expression}.click()`);};
const results=[];const check=(label,condition)=>{if(!condition)throw new Error('FAIL '+label);results.push('PASS '+label);console.log(results.at(-1));};
try{
  const target=await send('Target.createTarget',{url:'about:blank'},null);session=(await send('Target.attachToTarget',{targetId:target.targetId,flatten:true},null)).sessionId;
  await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
  await send('Page.navigate',{url:'http://localhost:3000'});await waitFor("document.querySelector('.metrics') && document.querySelectorAll('.metric').length===4");
  check('dashboard renders persisted statistics',await evaluate("document.querySelector('.metrics').innerText.includes('Approved headcount')"));
  const snap=async name=>{const r=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(resolve(output,name+'.png'),Buffer.from(r.data,'base64'));};
  await snap('desktop-overview');
  check('official Mechlin logo loads locally',await evaluate("document.querySelector('.company-logo img').complete && document.querySelector('.company-logo img').naturalWidth>0"));
  check('Orbit product branding appears in the workspace',await evaluate("document.querySelector('.product-brand').innerText.includes('Orbit')"));
  for(const view of ['Requisitions','Candidates','Pipeline','Interviews','Referrals','Administration','Settings','Audit log','Pipeline settings','Integrations']){
    await click(`document.querySelector('[data-nav="${view}"]')`);await waitFor(`document.querySelector('#main h1')?.textContent===${JSON.stringify(view)}`);
    check(view+' renders without load error',!(await evaluate("document.querySelector('#main').innerText.includes('Could not load')")));
    if(['Pipeline','Administration','Candidates','Settings'].includes(view))await snap('desktop-'+view.toLowerCase());
  }
  await click(`document.querySelector('[data-nav="Settings"]')`);await waitFor("document.querySelector('#appearance-form')!==null");
  check('admin sees three labeled theme controls',await evaluate("document.querySelectorAll('#appearance-form input[type=radio]').length===3 && [...document.querySelectorAll('#appearance-form input')].every(i=>i.closest('label'))"));
  await click(`document.querySelector('input[value="midnight"]')`);
  check('theme preview changes the current view immediately',await evaluate("document.documentElement.dataset.theme==='midnight' && !document.querySelector('#save-theme').disabled"));
  check('preview does not mutate the persisted workspace theme',await evaluate("fetch('/api/appearance').then(r=>r.json()).then(r=>r.theme==='mechlin')"));
  await click(`document.querySelector('[data-action="reset-theme"]')`);
  check('reset restores saved theme without saving',await evaluate("document.documentElement.dataset.theme==='mechlin' && document.querySelector('#save-theme').disabled"));
  for(const theme of ['midnight','ocean','mechlin']){
    await click(`document.querySelector('input[value="${theme}"]')`);await click(`document.querySelector('#save-theme')`);
    await waitFor(`document.querySelector('#save-theme')?.disabled && document.querySelector('#appearance-status')?.textContent.includes('saved workspace theme') && document.documentElement.dataset.theme==='${theme}'`);
    check(theme+' theme saves through the admin form',await evaluate(`fetch('/api/appearance').then(r=>r.json()).then(r=>r.theme==='${theme}')`));
    await evaluate("document.querySelector('#notice').textContent=''");await snap('settings-'+theme);
    await send('Page.reload');await waitFor(`document.querySelector('.metrics')!==null && document.documentElement.dataset.theme==='${theme}'`);
    check(theme+' theme persists after a full page reload',true);
    await snap('overview-'+theme);
    for(const view of ['Candidates','Pipeline','Interviews','Administration']){
      await click(`document.querySelector('[data-nav="${view}"]')`);await waitFor(`document.querySelector('#main h1')?.textContent===${JSON.stringify(view)}`);
      check(`${theme}: ${view} loads with saved theme`,await evaluate(`document.documentElement.dataset.theme==='${theme}' && !document.querySelector('#main').innerText.includes('Could not load')`));
    }
    await click(`document.querySelector('[data-nav="Settings"]')`);await waitFor("document.querySelector('#appearance-form')!==null");
    await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
    check(`${theme}: mobile theme settings stay within the viewport`,await evaluate('document.documentElement.scrollWidth<=window.innerWidth'));
    await snap('mobile-settings-'+theme);
    await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
  }
  await click(`document.querySelector('[data-nav="Candidates"]')`);await waitFor(`document.querySelector('[data-action="new-candidate"]')!==null`);
  await click(`document.querySelector('[data-action="new-candidate"]')`);await waitFor("document.querySelector('dialog').open");
  check('candidate form fields have labels',await evaluate("[...document.querySelectorAll('#edit-form input,#edit-form textarea')].every(e=>e.closest('label'))"));
  await evaluate(`{const f=document.querySelector('#edit-form');for(const [k,v] of Object.entries({name:'Browser Test <b>Candidate</b>',email:'browser-test@example.com',phone:'',team:'Engineering',skills:'SQL, JavaScript',source:'Referral',resume_text:'Experience with SQL and JavaScript.'}))f.elements[k].value=v;f.requestSubmit();}`);
  await waitFor("!document.querySelector('dialog').open && document.querySelector('#main').innerText.includes('browser-test@example.com')");
  check('candidate form saves and refreshes directory',true);
  check('candidate content is escaped against markup injection',await evaluate("document.querySelector('#candidate-table').innerHTML.includes('&lt;b&gt;Candidate&lt;/b&gt;') && !document.querySelector('#candidate-table b')"));
  await evaluate(`{const q=document.querySelector('#candidate-search');q.value='browser-test';q.dispatchEvent(new Event('input'));}`);
  check('candidate search filters rows',await evaluate("document.querySelectorAll('#candidate-table tbody tr').length===1"));
  await click(`document.querySelector('[data-action="new-candidate"]')`);
  await evaluate(`{const f=document.querySelector('#edit-form');for(const [k,v] of Object.entries({name:'Duplicate',email:'browser-test@example.com',team:'Engineering',source:'Direct',skills:''}))f.elements[k].value=v;f.requestSubmit();}`);
  await waitFor("document.querySelector('#form-error').textContent.includes('already exists')");
  check('duplicate error preserves form and user input',await evaluate("document.querySelector('dialog').open && document.querySelector('[name=name]').value==='Duplicate'"));
  await click(`document.querySelector('#close-modal')`);
  await click(`document.querySelector('[data-nav="Overview"]')`);await waitFor("document.querySelector('.metrics')!==null");
  await evaluate("document.querySelector('#notice').textContent=''");
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  check('mobile dashboard fits viewport',await evaluate('document.documentElement.scrollWidth<=window.innerWidth'));
  await snap('mobile-overview');
  await click(`document.querySelector('[data-nav="Pipeline"]')`);await waitFor("document.querySelector('.board')!==null");
  check('mobile pipeline uses contained horizontal scrolling',await evaluate('document.documentElement.scrollWidth<=window.innerWidth && document.querySelector(".board").scrollWidth>document.querySelector(".board").clientWidth'));
  await snap('mobile-pipeline');
  await click(`document.querySelector('[data-nav="Settings"]')`);await waitFor("document.querySelector('#appearance-form')!==null");
  await evaluate("document.querySelector('input[value=mechlin]').focus()");
  await send('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39});
  await send('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39});
  check('keyboard arrow navigation previews the next theme',await evaluate("document.activeElement.value==='midnight' && document.documentElement.dataset.theme==='midnight'"));
  await click(`document.querySelector('[data-action="reset-theme"]')`);
  check('PWA manifest uses Orbit branding',await evaluate("fetch('/manifest.webmanifest').then(r=>r.json()).then(r=>r.name==='Mechlin Orbit' && r.short_name==='Orbit')"));
  check('PWA icons and offline page are available',await evaluate("Promise.all(['/icon.svg','/icon-192.png','/icon-512.png','/offline.html'].map(url=>fetch(url).then(r=>r.ok))).then(r=>r.every(Boolean))"));
  await click(`document.querySelector('[data-action="logout"]')`);await waitFor("document.querySelector('.login-card')!==null");
  check('sign out returns to Microsoft-only login',await evaluate("document.querySelector('.login-card a').textContent.trim()==='Sign in with Microsoft 365'"));
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await snap('desktop-login');
  await send('Page.navigate',{url:'http://localhost:3000/?access=pending'});await waitFor("document.querySelector('.notice-inline')!==null");
  check('pending access notice explains approval requirement',await evaluate("document.querySelector('.notice-inline').textContent.includes('Access pending approval')"));
  check('no browser runtime exceptions',exceptions.length===0);
  writeFileSync(resolve(output,'BROWSER_RESULTS.txt'),`${results.join('\n')}\nChecks: ${results.length}; failed: 0\nBrowser: ${JSON.stringify(await send('Browser.getVersion',{},null))}\nSynthetic in-memory data; no live Entra authentication.\n`);
}catch(error){console.error('BROWSER FAILURE',error.message);try{console.error('PAGE',await evaluate('document.body.innerText'));console.error('EXCEPTIONS',JSON.stringify(exceptions));const shot=await send('Page.captureScreenshot',{format:'png'});writeFileSync(resolve(output,'browser-failure.png'),Buffer.from(shot.data,'base64'));}catch{console.error('Browser diagnostics unavailable.');}throw error;}finally{await send('Browser.close',{},null).catch(()=>{});ws.close();chrome.kill();app.close();}
